CREATE TABLE CONTENTSERVER.INPAYMENT_SUMMARY AS
SELECT REGION_ID,
       FLAG_NAME,
       SUM(FLAG_VALUE) AS FOUND,
       SUM(CASE WHEN FLAG_VALUE = 0 THEN 1 ELSE 0 END) AS MISSING
FROM (
    SELECT REGION_ID, 'BRM' AS FLAG_NAME, BRM AS FLAG_VALUE FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'LO_CAPTURE', LO_CAPTURE FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'LO', LO FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'MIS', MIS FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'ECMIS', ECMIS FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'OGA', OGA FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'CS', CS FROM CONTENTSERVER.INPAYMENTMONTHLY
) FLAG_DATA
GROUP BY REGION_ID, FLAG_NAME
ORDER BY REGION_ID, FLAG_NAME;

MERGE INTO CONTENTSERVER.INPAYMENT_TOTALS tgt
USING (
    SELECT REGION_ID, COUNT(*) AS TOTAL
    FROM INPAYMENTMONTHLY
    GROUP BY REGION_ID
) src
ON (tgt.REGION_ID = src.REGION_ID)
WHEN MATCHED THEN
    UPDATE SET tgt.TOTAL = src.TOTAL
WHEN NOT MATCHED THEN
    INSERT (REGION_ID, TOTAL) VALUES (src.REGION_ID, src.TOTAL);

-- Optionally remove regions no longer present:
DELETE FROM CONTENTSERVER.INPAYMENT_TOTALS t
WHERE NOT EXISTS (
    SELECT 1 FROM INPAYMENTMONTHLY m WHERE m.REGION_ID = t.REGION_ID
);