CREATE TABLE CONTENTSERVER.INPAYMENT_SUMMARY AS
SELECT REGION_ID,
       FLAG_NAME,
       SUM(FLAG_VALUE) AS FOUND,
       SUM(CASE WHEN FLAG_VALUE = 0 THEN 1 ELSE 0 END) AS MISSING
FROM (
    SELECT REGION_ID, 'BRM' AS FLAG_NAME, BRM AS FLAG_VALUE FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'LO_CAPTURE', LO_CAPTURE FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'LO', LO FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'MIS', MIS FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'ECMIS', ECMIS FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'OGA', OGA FROM CONTENTSERVER.INPAYMENTMONTHLY
    UNION ALL
    SELECT REGION_ID, 'CS', CS FROM CONTENTSERVER.INPAYMENTMONTHLY
) FLAG_DATA
GROUP BY REGION_ID, FLAG_NAME
ORDER BY REGION_ID, FLAG_NAME;