Select * FROM DC_FILE
WHERE rowid not in
(SELECT MIN(rowid)
FROM DC_FILE
GROUP BY BRM_BARCODE);
commit;

DELETE FROM DC_FILE
WHERE rowid not in
(SELECT MIN(rowid)
FROM DC_FILE
GROUP BY BRM_BARCODE);
commit;

CREATE UNIQUE INDEX IDX_BARCODE ON DC_FILE (BRM_BARCODE ASC) 
LOGGING 
TABLESPACE CONTENTSERVER_INDX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;