INSERT INTO HK_ECMIS (ID_NUMBER,NAME,SURNAME,GRANT_TYPE,REGION_ID)
SELECT TRIM(ID_NUMBER),TRIM(NAME),TRIM(SURNAME),TRIM(GRANT_TYPE),TRIM(REGION_CODE)
FROM SS_APP s
WHERE not exists(SELECT 1 from HK_ECMIS WHERE ID_NUMBER = TRIM(s.ID_NUMBER)AND GRANT_TYPE = TRIM(s.GRANT_TYPE))

INSERT INTO HK_ECMIS (ID_NUMBER, NAME, SURNAME, GRANT_TYPE, REGION_ID)
SELECT s.ID_NUMBER, TRIM(s.NAME), TRIM(s.SURNAME), TRIM(s.GRANT_TYPE), TRIM(s.REGION_CODE)
FROM SS_APPLICATION s
LEFT JOIN HK_ECMIS h ON h.ID_NUMBER = s.ID_NUMBER AND h.GRANT_TYPE = s.GRANT_TYPE
WHERE h.ID_NUMBER IS NULL;
