MERGE INTO DC_SOCPEN d
USING (
    SELECT DISTINCT
        c.PENSION_NO AS BENEFICIARY_ID,
        c.ID_NO AS CHILD_ID,
        B.NAME_EXT,
        B.SURNAME_EXT,
        C.GRANT_TYPE AS GRANT_TYPE,
        R.REGION_CODE AS REGION_ID,
        C.APPLICATION_DATE AS APPLICATION_DATE,
        C.STATUS_CODE,
        B.secondary_paypoint AS paypoint  
    FROM SASSA.socpen_personal_grants a
    JOIN SASSA.SOCPEN_PERSONAL B ON  LPAD(A.PENSION_NO, 13, '0') =  LPAD(b.PENSION_NO, 13, '0')
    INNER JOIN VW_P12_CHILDREN c ON c.PENSION_NO =  LPAD(A.PENSION_NO, 13, '0')
    LEFT JOIN SASSA.CUST_RESCODES R ON B.secondary_paypoint = R.RES_CODE
) src
ON (d.BENEFICIARY_ID = src.BENEFICIARY_ID AND d.GRANT_TYPE = src.GRANT_TYPE AND d.CHILD_ID = src.CHILD_ID AND d.SRD_NO is null)
WHEN NOT MATCHED THEN 
INSERT (BENEFICIARY_ID, CHILD_ID, NAME, SURNAME, GRANT_TYPE, REGION_ID, APPLICATION_DATE, STATUS_CODE, PAYPOINT)
VALUES (src.BENEFICIARY_ID, src.CHILD_ID, src.NAME_EXT, src.SURNAME_EXT, src.GRANT_TYPE, src.REGION_ID, src.APPLICATION_DATE, src.STATUS_CODE, src.PAYPOINT);
commit;