MERGE INTO DC_SOCPEN d
USING (
    SELECT DISTINCT 
        LPAD(A.PENSION_NO, 13, '0') AS BENEFICIARY_ID,
        A.GRANT_TYPE AS GRANT_TYPE,
        NULL AS CHILD_ID,
        NULL AS SRD_NO,
        B.NAME_EXT,
        B.SURNAME_EXT,
        D.REGION_CODE AS REGION_ID,
        A.APPLICATION_DATE AS APPLICATION_DATE,
        CASE 
            WHEN A.PRIM_STATUS IN ('B','A','9') AND A.SEC_STATUS IN ('2') THEN 'ACTIVE' 
            ELSE 'INACTIVE' 
        END AS STATUS_CODE,
        B.secondary_paypoint AS paypoint  
    FROM SASSA.socpen_personal_grants A
    JOIN SASSA.SOCPEN_PERSONAL B ON LPAD(A.PENSION_NO, 13, '0') = LPAD(B.PENSION_NO, 13, '0')
    JOIN SASSA.CUST_RESCODES D ON B.secondary_paypoint = D.RES_CODE
    WHERE A.GRANT_TYPE IN ('0','1','3','7','8','4')
    AND A.APPLICATION_DATE > to_date('31/DEC/2012')
) src
ON (d.BENEFICIARY_ID = src.BENEFICIARY_ID AND d.GRANT_TYPE = src.GRANT_TYPE AND d.CHILD_ID is null  AND d.SRD_no is null)
WHEN NOT MATCHED THEN 
INSERT (BENEFICIARY_ID, CHILD_ID, NAME, SURNAME, GRANT_TYPE, REGION_ID, APPLICATION_DATE, STATUS_CODE, PAYPOINT)
VALUES (src.BENEFICIARY_ID, src.CHILD_ID, src.NAME_EXT, src.SURNAME_EXT, src.GRANT_TYPE, src.REGION_ID, src.APPLICATION_DATE, src.STATUS_CODE, src.PAYPOINT);
