-- NO semicolons(;) at the end of the SQL statements in this file!

MERGE INTO DC_SOCPEN d
USING (
    SELECT DISTINCT
        A.SRD_NO,
        NVL(A.BENEFICIARY_ID, 'S' || LPAD(A.SRD_NO, 12, '0')) AS BENEFICIARY_ID,
        A.NAME,
        A.SURNAME,
        'S' AS GRANT_TYPE,
        A.PROVINCE AS REGION_ID,
        A.APPLICATION_DATE,
        A.STATUS_CODE,
        A.PAYPOINT
    FROM VW_MAX_SRD_TYPE A
) src
ON (d.SRD_NO = src.SRD_NO)
WHEN NOT MATCHED THEN 
INSERT (SRD_NO, BENEFICIARY_ID, NAME, SURNAME, GRANT_TYPE, REGION_ID, APPLICATION_DATE, STATUS_CODE, PAYPOINT)
VALUES (src.SRD_NO, src.BENEFICIARY_ID, src.NAME, src.SURNAME, src.GRANT_TYPE, src.REGION_ID, src.APPLICATION_DATE, src.STATUS_CODE, src.PAYPOINT)
